# Generated by Django 5.0.3 on 2024-10-15 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_alter_factura_fecha_alter_mesa_numero'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='documento',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='expedicion',
            field=models.DateField(null=True),
        ),
    ]
