# Generated by Django 5.0.3 on 2025-05-12 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_alter_user_documento'),
    ]

    operations = [
        migrations.AddField(
            model_name='factura',
            name='visible',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='mesa',
            name='descripcion',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='mesa',
            name='tipo',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='mesa',
            name='visible',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='visible',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='visible',
            field=models.BooleanField(default=True),
        ),
    ]
