# Generated by Django 5.0.3 on 2025-05-12 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_factura_visible_mesa_descripcion_mesa_tipo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mesa',
            name='capacidad',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
