# Generated by Django 5.0.3 on 2025-05-12 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_mesa_capacidad'),
    ]

    operations = [
        migrations.AddField(
            model_name='mesa',
            name='estado',
            field=models.BooleanField(default=True),
        ),
    ]
