# Generated by Django 5.0.3 on 2025-05-12 05:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_mesa_estado'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mesa',
            old_name='estado',
            new_name='disponible',
        ),
    ]
