# Generated by Django 5.0.3 on 2025-05-12 05:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_rename_estado_mesa_disponible'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mesa',
            name='capacidad',
        ),
    ]
