# Generated by Django 5.0.3 on 2025-06-03 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_remove_mesa_capacidad'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_client',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='producto',
            name='imgProducto',
            field=models.ImageField(null=True, upload_to='img/'),
        ),
    ]
